# Generated by Django 5.2.17 on 2026-09-26 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='support.staff'),
        ),
    ]
