# Generated by Django 5.2.17 on 2026-09-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_ticket_assigned_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pending_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
