# Generated by Django 5.2.17 on 2026-09-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_ticket_pending_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolution_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
